# Colors (umbraline)
# Gruvbox-inspired palette with 3 main accents:
# Yellow (functions/types/constants), Green (strings), Red (errors)
# "lack" blue as cool neutral hint color

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#fbf1c7'

# Cursor colors
[colors.cursor]
cursor = '#fbf1c7'
text = '#1d2021'

# Selection colors
[colors.selection]
background = '#2f3836'
text = '#fbf1c7'

# Normal colors (matching Neovim terminal ANSI)
[colors.normal]
black   = '#504945'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#83a598'
cyan    = '#83a598'
white   = '#fbf1c7'

# Bright colors (matching Neovim terminal ANSI)
[colors.bright]
black   = '#928374'
red     = '#d98a93'
green   = '#c7d5c0'
yellow  = '#dbd3bd'
blue    = '#c0cad4'
magenta = '#c0cad4'
cyan    = '#c0cad4'
white   = '#fbf1c7'

# Dim colors
[colors.dim]
black   = '#141617'
red     = '#a0454e'
green   = '#7a7d1e'
yellow  = '#a1834c'
blue    = '#566c64'
magenta = '#566c64'
cyan    = '#566c64'
white   = '#a89984'
